// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb.h for the primary calling header

#ifndef VERILATED_VTB___024ROOT_H_
#define VERILATED_VTB___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb__DOT__clk;
        CData/*0:0*/ tb__DOT__rst_n;
        CData/*2:0*/ tb__DOT__mode;
        CData/*3:0*/ tb__DOT__s_axis_tkeep;
        CData/*0:0*/ tb__DOT__s_axis_tvalid;
        CData/*3:0*/ tb__DOT__m_axis_tkeep;
        CData/*0:0*/ tb__DOT__m_axis_tready;
        CData/*0:0*/ tb__DOT__saw_msg_len_zero;
        CData/*0:0*/ tb__DOT__saw_msg_len_partial_word;
        CData/*0:0*/ tb__DOT__saw_msg_len_full_word;
        CData/*0:0*/ tb__DOT__saw_msg_len_block_aligned;
        CData/*0:0*/ tb__DOT__saw_msg_len_rate_minus_one;
        CData/*0:0*/ tb__DOT__saw_msg_len_multi_block;
        CData/*0:0*/ tb__DOT__saw_out_len_partial_word;
        CData/*0:0*/ tb__DOT__saw_out_len_block_aligned;
        CData/*0:0*/ tb__DOT__saw_out_len_multi_block;
        CData/*0:0*/ tb__DOT__saw_input_stall;
        CData/*0:0*/ tb__DOT__saw_output_stall;
        CData/*7:0*/ tb__DOT____Vlvbound_h639cd528__0;
        CData/*7:0*/ tb__DOT____Vlvbound_h949cbb31__0;
        CData/*7:0*/ tb__DOT____Vlvbound_h570ad72a__0;
        CData/*7:0*/ tb__DOT____Vlvbound_h54bcd3e1__0;
        CData/*7:0*/ tb__DOT____Vlvbound_h5a85157f__0;
        CData/*7:0*/ tb__DOT____Vlvbound_hbe8357a8__0;
        CData/*2:0*/ tb__DOT__dut__DOT__state_n;
        CData/*2:0*/ tb__DOT__dut__DOT__state_r;
        CData/*4:0*/ tb__DOT__dut__DOT__round_cnt_r;
        CData/*4:0*/ tb__DOT__dut__DOT__round_cnt_offset;
        CData/*7:0*/ tb__DOT__dut__DOT__byte_cnt_r;
        CData/*5:0*/ tb__DOT__dut__DOT__block_cnt_r;
        CData/*3:0*/ tb__DOT__dut__DOT__wdata_mask_be;
        CData/*2:0*/ tb__DOT__dut__DOT__valid_inbits;
        CData/*7:0*/ tb__DOT__dut__DOT__sha3_rate;
        CData/*7:0*/ tb__DOT__dut__DOT__sha3_suffix;
        CData/*4:0*/ tb__DOT__dut__DOT__rounds;
        CData/*7:0*/ tb__DOT__dut__DOT____Vlvbound_h22a8ff8e__0;
        CData/*7:0*/ tb__DOT__dut__DOT____Vlvbound_h1c9f0a89__0;
        CData/*7:0*/ tb__DOT__dut__DOT____Vlvbound_h075e1975__0;
        CData/*7:0*/ tb__DOT__dut__DOT____Vlvbound_h1c9f0a89__1;
        CData/*7:0*/ tb__DOT__dut__DOT____Vlvbound_h49573fc5__0;
        CData/*7:0*/ tb__DOT__dut__DOT____Vlvbound_h1c9f0a89__2;
        CData/*7:0*/ tb__DOT__dut__DOT____Vlvbound_h1c9f0a89__3;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb__DOT__rst_n__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ tb__DOT__inblocks;
        SData/*15:0*/ tb__DOT__inlen_partial;
        SData/*15:0*/ tb__DOT__outblocks;
        SData/*15:0*/ tb__DOT__outlen_partial;
        IData/*31:0*/ tb__DOT__s_axis_tdata;
        IData/*31:0*/ tb__DOT__tests_run;
        IData/*31:0*/ tb__DOT__bytes_checked;
        IData/*31:0*/ tb__DOT__unnamedblk29__DOT__mode_i;
        IData/*31:0*/ tb__DOT__unnamedblk29__DOT__unnamedblk30__DOT__rate;
        IData/*31:0*/ tb__DOT__dut__DOT__rdata_mask;
        IData/*31:0*/ tb__DOT__dut__DOT__rdata_masked;
        IData/*31:0*/ tb__DOT__dut__DOT__suffix_word_masked;
        IData/*31:0*/ tb__DOT__dut__DOT__sha3_suffix_word;
        IData/*31:0*/ tb__DOT__dut__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ tb__DOT__dut__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ tb__DOT__dut__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__1__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__1__msg_len;
    };
    struct {
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__1__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__1__input_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__1__output_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__3__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__3__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__3__rate;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__3__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__3__round_offset_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__3__msg_idx;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__3__out_idx;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__15__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__15__round_offset_i;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__16__x;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__16__y;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__21__x;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__21__y;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__39__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__39__msg_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__39__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__39__input_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__39__output_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__41__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__41__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__41__rate;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__41__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__41__round_offset_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__41__msg_idx;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__41__out_idx;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__53__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__53__round_offset_i;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__54__x;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__54__y;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__59__x;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__59__y;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__77__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__77__msg_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__77__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__77__input_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__77__output_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__79__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__79__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__79__rate;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__79__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__79__round_offset_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__79__msg_idx;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__79__out_idx;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__91__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__91__round_offset_i;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__92__x;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__92__y;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__97__x;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__97__y;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__115__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__115__msg_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__115__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__115__input_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__115__output_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__117__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__117__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__117__rate;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__117__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__117__round_offset_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__117__msg_idx;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__117__out_idx;
    };
    struct {
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__129__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__129__round_offset_i;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__130__x;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__130__y;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__135__x;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__135__y;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__153__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__153__msg_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__153__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__153__input_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__153__output_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__154__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__154__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__154__rate;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__154__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__154__round_offset_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__154__msg_idx;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__154__out_idx;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__166__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__166__round_offset_i;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__167__x;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__167__y;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__172__x;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__172__y;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__190__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__190__msg_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__190__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__190__input_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__190__output_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__191__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__191__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__191__rate;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__191__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__191__round_offset_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__191__msg_idx;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__191__out_idx;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__203__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__203__round_offset_i;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__204__x;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__204__y;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__209__x;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__209__y;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__227__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__227__msg_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__227__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__227__input_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__227__output_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__228__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__228__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__228__rate;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__228__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__228__round_offset_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__228__msg_idx;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__228__out_idx;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__240__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__240__round_offset_i;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__241__x;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__241__y;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__246__x;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__246__y;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__264__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__264__msg_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__264__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__264__input_stall_percent;
    };
    struct {
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__264__output_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__265__mode_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__265__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__265__rate;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__265__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__265__round_offset_i;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__265__msg_idx;
        IData/*31:0*/ __Vtask_tb__DOT__sponge_reference__265__out_idx;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__277__rounds_i;
        IData/*31:0*/ __Vtask_tb__DOT__keccak_p1600__277__round_offset_i;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__278__x;
        IData/*31:0*/ __Vfunc_tb__DOT__load_lane__278__y;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__283__x;
        IData/*31:0*/ __Vtask_tb__DOT__store_lane__283__y;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__302__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__302__input_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__302__output_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__339__out_len;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__339__input_stall_percent;
        IData/*31:0*/ __Vtask_tb__DOT__run_one_test__339__output_stall_percent;
        IData/*31:0*/ __Vfunc_rc__377__round;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ tb__DOT____Vlvbound_h83f8a995__0;
        QData/*63:0*/ tb__DOT____Vlvbound_h2bf91d87__0;
        QData/*63:0*/ tb__DOT____Vlvbound_h45a19556__0;
        QData/*63:0*/ tb__DOT____Vlvbound_hacfd4734__0;
        QData/*63:0*/ tb__DOT____Vlvbound_h4bdc605f__0;
        QData/*63:0*/ tb__DOT____Vlvbound_h63d661c9__0;
        QData/*63:0*/ __Vtask_tb__DOT__store_lane__21__lane;
        QData/*63:0*/ __Vtask_tb__DOT__store_lane__59__lane;
        QData/*63:0*/ __Vtask_tb__DOT__store_lane__97__lane;
        QData/*63:0*/ __Vtask_tb__DOT__store_lane__135__lane;
        QData/*63:0*/ __Vtask_tb__DOT__store_lane__172__lane;
        QData/*63:0*/ __Vtask_tb__DOT__store_lane__209__lane;
        QData/*63:0*/ __Vtask_tb__DOT__store_lane__246__lane;
        QData/*63:0*/ __Vtask_tb__DOT__store_lane__283__lane;
        QData/*63:0*/ __Vfunc_rc__377__Vfuncout;
        VlUnpacked<CData/*0:0*/, 8> tb__DOT__saw_mode;
        VlUnpacked<CData/*7:0*/, 200> tb__DOT__dut__DOT__kstate_n;
        VlUnpacked<CData/*7:0*/, 200> tb__DOT__dut__DOT__kstate_r;
        VlUnpacked<CData/*7:0*/, 200> tb__DOT__dut__DOT__kstate_out;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb__DOT__dut__DOT__keccak_f1600_inst__DOT__state_s;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb__DOT__dut__DOT__keccak_f1600_inst__DOT__theta;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb__DOT__dut__DOT__keccak_f1600_inst__DOT__rho;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb__DOT__dut__DOT__keccak_f1600_inst__DOT__pi;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb__DOT__dut__DOT__keccak_f1600_inst__DOT__chi;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> tb__DOT__dut__DOT__keccak_f1600_inst__DOT__iota;
        VlUnpacked<CData/*7:0*/, 200> __Vtask_tb__DOT__sponge_reference__3__state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> __Vtask_tb__DOT__keccak_p1600__15__a;
        VlUnpacked<CData/*7:0*/, 200> __Vfunc_tb__DOT__load_lane__16__state;
        VlUnpacked<CData/*7:0*/, 200> __Vtask_tb__DOT__sponge_reference__41__state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> __Vtask_tb__DOT__keccak_p1600__53__a;
        VlUnpacked<CData/*7:0*/, 200> __Vfunc_tb__DOT__load_lane__54__state;
        VlUnpacked<CData/*7:0*/, 200> __Vtask_tb__DOT__sponge_reference__79__state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> __Vtask_tb__DOT__keccak_p1600__91__a;
        VlUnpacked<CData/*7:0*/, 200> __Vfunc_tb__DOT__load_lane__92__state;
        VlUnpacked<CData/*7:0*/, 200> __Vtask_tb__DOT__sponge_reference__117__state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> __Vtask_tb__DOT__keccak_p1600__129__a;
        VlUnpacked<CData/*7:0*/, 200> __Vfunc_tb__DOT__load_lane__130__state;
        VlUnpacked<CData/*7:0*/, 200> __Vtask_tb__DOT__sponge_reference__154__state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> __Vtask_tb__DOT__keccak_p1600__166__a;
        VlUnpacked<CData/*7:0*/, 200> __Vfunc_tb__DOT__load_lane__167__state;
        VlUnpacked<CData/*7:0*/, 200> __Vtask_tb__DOT__sponge_reference__191__state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> __Vtask_tb__DOT__keccak_p1600__203__a;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 200> __Vfunc_tb__DOT__load_lane__204__state;
        VlUnpacked<CData/*7:0*/, 200> __Vtask_tb__DOT__sponge_reference__228__state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> __Vtask_tb__DOT__keccak_p1600__240__a;
        VlUnpacked<CData/*7:0*/, 200> __Vfunc_tb__DOT__load_lane__241__state;
        VlUnpacked<CData/*7:0*/, 200> __Vtask_tb__DOT__sponge_reference__265__state;
        VlUnpacked<VlUnpacked<QData/*63:0*/, 5>, 5> __Vtask_tb__DOT__keccak_p1600__277__a;
        VlUnpacked<CData/*7:0*/, 200> __Vfunc_tb__DOT__load_lane__278__state;
        VlUnpacked<CData/*0:0*/, 14> __Vm_traceActivity;
    };
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__1__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__1__got;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__3__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__3__digest;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__39__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__39__got;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__41__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__41__digest;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__77__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__77__got;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__79__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__79__digest;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__115__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__115__got;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__117__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__117__digest;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__153__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__153__got;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__154__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__154__digest;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__190__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__190__got;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__191__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__191__digest;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__227__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__227__got;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__228__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__228__digest;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__264__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__264__got;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__265__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__sponge_reference__265__digest;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__302__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__302__got;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__339__msg;
    VlQueue<CData/*7:0*/> __Vtask_tb__DOT__run_one_test__339__got;
    std::string __Vtask_tb__DOT__run_one_test__1__test_name;
    std::string __Vtask_tb__DOT__run_one_test__39__test_name;
    std::string __Vtask_tb__DOT__run_one_test__77__test_name;
    std::string __Vtask_tb__DOT__run_one_test__115__test_name;
    std::string __Vtask_tb__DOT__run_one_test__153__test_name;
    std::string __Vtask_tb__DOT__run_one_test__190__test_name;
    std::string __Vtask_tb__DOT__run_one_test__227__test_name;
    std::string __Vtask_tb__DOT__run_one_test__264__test_name;
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h95cd0708__0;
    VlForkSync __Vfork_1__sync;
    VlForkSync __Vfork_2__sync;
    VlForkSync __Vfork_3__sync;
    VlForkSync __Vfork_4__sync;
    VlForkSync __Vfork_5__sync;
    VlForkSync __Vfork_6__sync;
    VlForkSync __Vfork_7__sync;
    VlForkSync __Vfork_8__sync;
    VlForkSync __Vfork_9__sync;
    VlForkSync __Vfork_10__sync;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb___024root(Vtb__Syms* symsp, const char* v__name);
    ~Vtb___024root();
    VL_UNCOPYABLE(Vtb___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
