#!/usr/bin/env python3
"""Generate regression vectors and golden outputs for sha3.

Golden-data provenance:
  - SHA3-224/256/384/512 and SHAKE128/256 are generated with Python hashlib,
    whose SHA-3/SHAKE constructors implement the FIPS 202 SHA-3 standard.
  - TurboSHAKE128/256 are generated by the Keccak-p[1600,12] sponge model in
    this file, following RFC 9861 "KangarooTwelve and TurboSHAKE".

References:
  - NIST FIPS 202:
    https://csrc.nist.gov/pubs/fips/202/final
  - Python hashlib:
    https://docs.python.org/3/library/hashlib.html
  - RFC 9861:
    https://www.rfc-editor.org/rfc/rfc9861.html

Run from sha3:
    python3 sim/scripts/generate_regression_vectors.py --vector-set t1
    python3 sim/scripts/generate_regression_vectors.py --vector-set t2
"""

import argparse
import hashlib
from pathlib import Path

MASK64 = (1 << 64) - 1
MAX_INPUT_BYTES = 512
MAX_OUTPUT_BYTES = 512

MODE_ID = {
    "SHA3_224": 0,
    "SHA3_256": 1,
    "SHA3_384": 2,
    "SHA3_512": 3,
    "SHAKE128": 4,
    "SHAKE256": 5,
    "TURBOSHAKE128": 6,
    "TURBOSHAKE256": 7,
}

FLAG_INPUT_BUBBLES = 0x01
FLAG_OUTPUT_BACKPRESSURE = 0x02

MODE_INFO = {
    "SHA3_224": {"rate": 144, "out_len": 28, "xof": False},
    "SHA3_256": {"rate": 136, "out_len": 32, "xof": False},
    "SHA3_384": {"rate": 104, "out_len": 48, "xof": False},
    "SHA3_512": {"rate": 72, "out_len": 64, "xof": False},
    "SHAKE128": {"rate": 168, "out_len": 32, "xof": True},
    "SHAKE256": {"rate": 136, "out_len": 64, "xof": True},
    "TURBOSHAKE128": {"rate": 168, "out_len": 64, "xof": True},
    "TURBOSHAKE256": {"rate": 136, "out_len": 64, "xof": True},
}

ROT = [
    [0, 36, 3, 41, 18],
    [1, 44, 10, 45, 2],
    [62, 6, 43, 15, 61],
    [28, 55, 25, 21, 56],
    [27, 20, 39, 8, 14],
]

ROUND_CONSTANTS = [
    0x0000000000000001,
    0x0000000000008082,
    0x800000000000808A,
    0x8000000080008000,
    0x000000000000808B,
    0x0000000080000001,
    0x8000000080008081,
    0x8000000000008009,
    0x000000000000008A,
    0x0000000000000088,
    0x0000000080008009,
    0x000000008000000A,
    0x000000008000808B,
    0x800000000000008B,
    0x8000000000008089,
    0x8000000000008003,
    0x8000000000008002,
    0x8000000000000080,
    0x000000000000800A,
    0x800000008000000A,
    0x8000000080008081,
    0x8000000000008080,
    0x0000000080000001,
    0x8000000080008008,
]


def rol64(value, shift):
    if shift == 0:
        return value
    return ((value << shift) | (value >> (64 - shift))) & MASK64


def keccak_p(state, rounds=24, start_round=0):
    lanes = [[0 for _ in range(5)] for _ in range(5)]
    for y in range(5):
        for x in range(5):
            off = 8 * (x + 5 * y)
            lanes[x][y] = int.from_bytes(state[off : off + 8], "little")

    for rnd in range(start_round, start_round + rounds):
        c = [
            lanes[x][0] ^ lanes[x][1] ^ lanes[x][2] ^ lanes[x][3] ^ lanes[x][4]
            for x in range(5)
        ]
        d = [c[(x - 1) % 5] ^ rol64(c[(x + 1) % 5], 1) for x in range(5)]

        for x in range(5):
            for y in range(5):
                lanes[x][y] ^= d[x]

        b = [[0 for _ in range(5)] for _ in range(5)]
        for x in range(5):
            for y in range(5):
                b[y][(2 * x + 3 * y) % 5] = rol64(lanes[x][y], ROT[x][y])

        for x in range(5):
            for y in range(5):
                lanes[x][y] = (
                    b[x][y] ^ ((~b[(x + 1) % 5][y]) & b[(x + 2) % 5][y])
                ) & MASK64

        lanes[0][0] ^= ROUND_CONSTANTS[rnd]

    out = bytearray(200)
    for y in range(5):
        for x in range(5):
            off = 8 * (x + 5 * y)
            out[off : off + 8] = lanes[x][y].to_bytes(8, "little")
    return out


def sponge(msg, rate, suffix, out_len, rounds=24, start_round=0):
    state = bytearray(200)
    pos = 0

    while len(msg) - pos >= rate:
        for i, byte in enumerate(msg[pos : pos + rate]):
            state[i] ^= byte
        state = keccak_p(state, rounds, start_round)
        pos += rate

    tail = msg[pos:]
    for i, byte in enumerate(tail):
        state[i] ^= byte
    state[len(tail)] ^= suffix
    state[rate - 1] ^= 0x80
    state = keccak_p(state, rounds, start_round)

    out = bytearray()
    while len(out) < out_len:
        out.extend(state[: min(rate, out_len - len(out))])
        if len(out) < out_len:
            state = keccak_p(state, rounds, start_round)
    return bytes(out)


def golden_digest(mode, msg, out_len):
    if mode == "SHA3_224":
        return hashlib.sha3_224(msg).digest()[:out_len]
    if mode == "SHA3_256":
        return hashlib.sha3_256(msg).digest()[:out_len]
    if mode == "SHA3_384":
        return hashlib.sha3_384(msg).digest()[:out_len]
    if mode == "SHA3_512":
        return hashlib.sha3_512(msg).digest()[:out_len]
    if mode == "SHAKE128":
        return hashlib.shake_128(msg).digest(out_len)
    if mode == "SHAKE256":
        return hashlib.shake_256(msg).digest(out_len)
    if mode == "TURBOSHAKE128":
        return sponge(msg, 168, 0x1F, out_len, rounds=12, start_round=12)
    if mode == "TURBOSHAKE256":
        return sponge(msg, 136, 0x1F, out_len, rounds=12, start_round=12)
    raise ValueError(f"unsupported mode: {mode}")


def pattern(length, seed):
    return bytes(((seed + 17 * i + 31 * (i % 7)) & 0xFF) for i in range(length))


def flags_for_case(index):
    flags = 0
    if index % 3 == 1:
        flags |= FLAG_INPUT_BUBBLES
    if index % 4 == 2:
        flags |= FLAG_OUTPUT_BACKPRESSURE
    return flags


def message_for_case(mode, length, index):
    if length == 0:
        return b""
    if length == 1:
        return b"a"
    if length == 3:
        return b"abc"
    seed = (0x21 + 0x17 * MODE_ID[mode] + index) & 0xFF
    return pattern(length, seed)


def default_cases():
    cases = []

    for mode, info in MODE_INFO.items():
        rate = info["rate"]
        out_len = info["out_len"]
        input_lengths = [0, 1, 3, rate - 1, rate, rate + 1, 2 * rate + 3, 3 * rate + 5]

        for input_len in input_lengths:
            idx = len(cases)
            msg = message_for_case(mode, input_len, idx)
            cases.append((mode, msg, out_len, flags_for_case(idx)))

        if info["xof"]:
            output_lengths = [1, rate - 1, rate, rate + 1, 2 * rate + 3, 3 * rate + 5]
            msg = message_for_case(mode, rate + 1, len(cases))
            for output_len in output_lengths:
                idx = len(cases)
                cases.append((mode, msg, output_len, flags_for_case(idx)))

    return cases


def exhaustive_input_len_cases():
    cases = []

    for mode, info in MODE_INFO.items():
        rate = info["rate"]
        out_len = info["out_len"]
        for input_len in range(rate + 2):
            idx = len(cases)
            msg = message_for_case(mode, input_len, idx)
            cases.append((mode, msg, out_len, flags_for_case(idx)))

    return cases


def self_check():
    # NIST FIPS 202 known-answer checks for the empty message.
    assert hashlib.sha3_256(b"").hexdigest() == (
        "a7ffc6f8bf1ed76651c14756a061d662"
        "f580ff4de43b49fa82d80a4b80f8434a"
    )
    assert hashlib.shake_128(b"").digest(32).hex() == (
        "7f9c2ba4e88f827d616045507605853e"
        "d73b8093f6efbc88eb1a6eacfa66ef26"
    )

    # Cross-check the local Keccak sponge model against hashlib for standard
    # SHA3/SHAKE settings before using it for TurboSHAKE.
    assert sponge(b"", 136, 0x06, 32) == hashlib.sha3_256(b"").digest()
    assert sponge(b"abc", 136, 0x06, 32) == hashlib.sha3_256(b"abc").digest()
    assert sponge(b"abc", 168, 0x1F, 64) == hashlib.shake_128(b"abc").digest(64)

    # RFC 9861 Section 5 TurboSHAKE known-answer check:
    # TurboSHAKE128(M=empty, D=1F, outputByteLen=32).
    assert golden_digest("TURBOSHAKE128", b"", 32).hex() == (
        "1e415f1c5983aff2169217277d17bb53"
        "8cd945a397ddec541f1ce41af2c1b74c"
    )


def write_vectors(out_dir, cases):
    out_dir.mkdir(parents=True, exist_ok=True)
    meta_lines = []
    input_lines = []
    expected_lines = []

    for idx, (mode, msg, out_len, flags) in enumerate(cases):
        if len(msg) > MAX_INPUT_BYTES:
            raise ValueError(f"case {idx} input length exceeds MAX_INPUT_BYTES")
        if out_len > MAX_OUTPUT_BYTES:
            raise ValueError(f"case {idx} output length exceeds MAX_OUTPUT_BYTES")

        expected = golden_digest(mode, msg, out_len)
        meta = (flags << 56) | (MODE_ID[mode] << 48) | (len(msg) << 32) | (out_len << 16) | idx
        meta_lines.append(
            f"{meta:016x} // {idx}: {mode} in={len(msg)} out={out_len} flags=0x{flags:02x}\n"
        )

        for byte_idx in range(MAX_INPUT_BYTES):
            value = msg[byte_idx] if byte_idx < len(msg) else 0
            comment = f" // case {idx} {mode} input byte {byte_idx}" if byte_idx == 0 else ""
            input_lines.append(f"{value:02x}{comment}\n")

        for byte_idx in range(MAX_OUTPUT_BYTES):
            value = expected[byte_idx] if byte_idx < len(expected) else 0
            comment = f" // case {idx} {mode} expected byte {byte_idx}" if byte_idx == 0 else ""
            expected_lines.append(f"{value:02x}{comment}\n")

    (out_dir / "regression_count.hex").write_text(f"{len(cases):08x}\n")
    (out_dir / "regression_meta.hex").write_text("".join(meta_lines))
    (out_dir / "regression_input.hex").write_text("".join(input_lines))
    (out_dir / "regression_expected.hex").write_text("".join(expected_lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out-dir",
        default=None,
        type=Path,
        help="directory for generated .hex vector files",
    )
    parser.add_argument(
        "--vector-set",
        choices=("t1", "t2", "all"),
        default="t1",
        help="vector set to generate: t1=boundary regression, t2=input_len 0..rate+1 sweep",
    )
    args = parser.parse_args()

    self_check()
    case_sets = {
        "t1": default_cases,
        "t2": exhaustive_input_len_cases,
    }

    selected_sets = ("t1", "t2") if args.vector_set == "all" else (args.vector_set,)
    for vector_set in selected_sets:
        out_dir = args.out_dir if args.out_dir is not None else Path("sim/vectors") / vector_set
        cases = case_sets[vector_set]()
        write_vectors(out_dir, cases)
        print(f"Wrote {len(cases)} {vector_set} regression vectors to {out_dir}")


if __name__ == "__main__":
    main()
